GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTczMDgyMDEzNH0.gi2_FmGvsU7eD3hlkH2AyAM1upsxZGFIsi6IzKeqImc


###

DELETE http://localhost:4000/logout
Content-Type: application/json

{

"token": 
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTczMDgyMjM5OX0.eClHFOyn1bEO7si7xced66fMrSzBdvKILGvEO0T9Acc"

}


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTczMDgyMjM5OX0.eClHFOyn1bEO7si7xced66fMrSzBdvKILGvEO0T9Acc"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"

}